### ISSUE TITLE
Practica#4

### ISSUE THREAD

**Issue by 22620229Angel** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipo-osteas-b#1]
[Practica4.pdf](https://github.com/user-attachments/files/17117359/Practica4.pdf)

**Comment by ArcangelGC** [comment]
Confirmo de recibido.
En base a la rúbrica, nosotros como equipo les damos una calificación de 20/20.
Sugerencias poner un índice y el interlineado.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
